#!/bin/bash
# Creates migration vs runtime roles and the application database.
# Runs once as the Compose superuser on first volume init.
set -euo pipefail

OMNIDOC_DB="${OMNIDOC_DB:-omnidoc}"
OMNIDOC_MIGRATOR_USER="${OMNIDOC_MIGRATOR_USER:-omnidoc_migrator}"
OMNIDOC_MIGRATOR_PASSWORD="${OMNIDOC_MIGRATOR_PASSWORD:-omnidoc_migrator_dev}"
OMNIDOC_APP_USER="${OMNIDOC_APP_USER:-omnidoc_app}"
OMNIDOC_APP_PASSWORD="${OMNIDOC_APP_PASSWORD:-omnidoc_app_dev}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	DO \$\$
	BEGIN
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${OMNIDOC_MIGRATOR_USER}') THEN
	    CREATE ROLE ${OMNIDOC_MIGRATOR_USER} LOGIN PASSWORD '${OMNIDOC_MIGRATOR_PASSWORD}' BYPASSRLS;
	  ELSE
	    ALTER ROLE ${OMNIDOC_MIGRATOR_USER} BYPASSRLS;
	  END IF;
	  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${OMNIDOC_APP_USER}') THEN
	    CREATE ROLE ${OMNIDOC_APP_USER} LOGIN PASSWORD '${OMNIDOC_APP_PASSWORD}' NOBYPASSRLS;
	  ELSE
	    ALTER ROLE ${OMNIDOC_APP_USER} NOBYPASSRLS;
	  END IF;
	END
	\$\$;

	SELECT 'CREATE DATABASE ${OMNIDOC_DB} OWNER ${OMNIDOC_MIGRATOR_USER}'
	WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${OMNIDOC_DB}')\gexec

	GRANT CONNECT ON DATABASE ${OMNIDOC_DB} TO ${OMNIDOC_APP_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$OMNIDOC_DB" <<-EOSQL
	CREATE EXTENSION IF NOT EXISTS vector;

	GRANT USAGE ON SCHEMA public TO ${OMNIDOC_APP_USER};
	GRANT CREATE ON SCHEMA public TO ${OMNIDOC_MIGRATOR_USER};

	ALTER DEFAULT PRIVILEGES FOR ROLE ${OMNIDOC_MIGRATOR_USER} IN SCHEMA public
	  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${OMNIDOC_APP_USER};
	ALTER DEFAULT PRIVILEGES FOR ROLE ${OMNIDOC_MIGRATOR_USER} IN SCHEMA public
	  GRANT USAGE, SELECT ON SEQUENCES TO ${OMNIDOC_APP_USER};
EOSQL
